### ISSUE TITLE
Uncaught TypeError: Cannot read property 'level' of undefined

### ISSUE THREAD

**Issue by frankleonrose** [platformio/platformio-atom-ide-debugger#14]
[Enter steps to reproduce:]

1. While debugging (Feather, Blackmagic)
2. Had 4 breakpoints assigned and attempted to step. Failed because it needed a breakpoint available (presumably).
3. Went to debugger console and successfully deleted a breakpoint
4. Clicked Step button on debug control panel
5. Exception as detailed below. Simultaneously, got this popup ![image](https://user-images.githubusercontent.com/1261725/30250731-b7bce5fa-9621-11e7-85bf-1bf6f85aa817.png)

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [platformio-ide-debugger](https://github.com/platformio/platformio-atom-ide-debugger) package 1.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'level' of undefined

```
At /Users/frank/.atom/packages/platformio-ide-debugger/lib/mi/exec.coffee:131

TypeError: Cannot read property 'level' of undefined
    at ExecState._frameChanged (/packages/platformio-ide-debugger/lib/mi/exec.coffee:131:31)
    at ExecState._onExec (/packages/platformio-ide-debugger/lib/mi/exec.coffee:109:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at GDB._async_record_handler (/packages/platformio-ide-debugger/lib/mi/gdb.coffee:105:18)
    at GDB._line_output_handler (/packages/platformio-ide-debugger/lib/mi/gdb.coffee:99:32)
    at BufferedProcess._stdout (/packages/platformio-ide-debugger/lib/mi/utils/buffered-process.coffee:42:14)
    at /packages/platformio-ide-debugger/lib/mi/utils/buffered-process.coffee:12:51)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -4:42.4.0 platformio-ide-debugger:disconnect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -3:30.9.0 editor:newline (input.hidden-input)
  2x -3:29.1.0 core:backspace (input.hidden-input)
     -3:25.5.0 core:save (input.hidden-input)
     -3:25.5.0 build:refresh-targets (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -3:17.5.0 platformio-ide:target:debug (input.hidden-input)
     -3:17.5.0 platformio-ide:target:debug-/Users/frank/project/otaa-lmic (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -2:35.8.0 platformio-ide-debugger:continue (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -2:33.8.0 platformio-ide-debugger:interrupt (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -2:31.9.0 platformio-ide-debugger:disconnect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -2:28.4.0 platformio-ide:target:debug (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
     -2:12.3.0 platformio-ide:target:debug (input.hidden-input)
     -2:12.3.0 platformio-ide:target:debug-/Users/frank/project/otaa-lmic (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
  3x -1:59.2.0 platformio-ide-debugger:next (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
  2x -1:40.5.0 platformio-ide-debugger:finish (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
diagrams 0.28.2 
file-icons 2.1.11 
intentions 1.1.5 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.8 
minimap 4.29.3 
parinfer 1.20.0 
platformio-ide 2.0.0-rc.2 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.6.0 
proto-repl 1.4.21 
proto-repl-charts 0.4.1 
regex-railroad-diagram 0.19.3 
tool-bar 1.1.0 
```

**Comment by ivankravets** [comment]
See comparison table: http://platformio.org/platformio-ide

We have experimental support for debugging in Atom. Could you try PIO IDE for VSCode?

Thanks!
