### ISSUE TITLE
Uncaught TypeError: Cannot read property '_deleted' of undefined

### ISSUE THREAD

**Issue by slavaz** [platformio/platformio-atom-ide-debugger#15]
[Enter steps to reproduce:]

1. Start new debug session
2. Wait for the error message

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: "Fedora release
**Thrown From**: [platformio-ide-debugger](https://github.com/platformio/platformio-atom-ide-debugger) package 1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property '_deleted' of undefined

```
At /home/slavaz/.atom/packages/platformio-ide-debugger/lib/mi/breaks.coffee:117

TypeError: Cannot read property '_deleted' of undefined
    at BreakpointManager.module.exports.BreakpointManager._onAsyncNotify (/packages/platformio-ide-debugger/lib/mi/breaks.coffee:117:29)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at GDB._async_record_handler (/packages/platformio-ide-debugger/lib/mi/gdb.coffee:105:18)
    at GDB._line_output_handler (/packages/platformio-ide-debugger/lib/mi/gdb.coffee:99:32)
    at BufferedProcess._stdout (/packages/platformio-ide-debugger/lib/mi/utils/buffered-process.coffee:42:14)
    at /packages/platformio-ide-debugger/lib/mi/utils/buffered-process.coffee:12:51)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -3:08.0 platformio-ide:target:upload-/home/slavaz/Документы/PlatformIO/Projects/stm32-test-cube (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:09.9.0 platformio-ide:target:debug (input.hidden-input)
     -2:09.9.0 platformio-ide:target:debug-/home/slavaz/Документы/PlatformIO/Projects/stm32-test-cube (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:35.8.0 platformio-ide-debugger:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:24.8.0 platformio-ide:target:debug (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:24.8.0 platformio-ide:target:debug-/home/slavaz/Документы/PlatformIO/Projects/stm32-test-cube (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:10 platformio-ide-debugger:interrupt (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:43.8.0 platformio-ide-debugger:toggle-breakpoint (input.hidden-input)
     -0:36.6.0 platformio-ide-debugger:interrupt (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:32 platformio-ide-debugger:disconnect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:19.8.0 build:toggle-panel (input.hidden-input)
     -0:11.5.0 platformio-ide:target:debug (input.hidden-input)
     -0:11.5.0 platformio-ide:target:debug-/home/slavaz/Документы/PlatformIO/Projects/stm32-test-cube (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.1.0 core:move-up (input.hidden-input)
     -0:06.8.0 core:move-down (input.hidden-input)
  2x -0:05.4.0 platformio-ide-debugger:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.22 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
tool-bar 1.1.7 
```

**Comment by ivankravets** [comment]
Please use PlatformIO IDE for VSCode https://platformio.org/get-started/ide?install=vscode

We will deprecate PIO IDE Debugger for Atom soon.

**Comment by slavaz** [comment]
got it
