### ISSUE TITLE
Failed to activate the platformio-ide-debugger package

### ISSUE THREAD

**Issue by cent0** [platformio/platformio-atom-ide-debugger#16]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-debugger](https://github.com/platformio/platformio-atom-ide-debugger) package 1.2.6

### Stack Trace

Failed to activate the platformio-ide-debugger package

```
At Cannot find module './gdbmi.js'

Error: Cannot find module './gdbmi.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/platformio-ide-debugger/lib/mi/gdb.coffee:3:12)
    at /packages/platformio-ide-debugger/lib/mi/gdb.coffee:1:1)
    at /packages/platformio-ide-debugger/lib/mi/gdb.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/platformio-ide-debugger/lib/main.coffee:2:7)
    at /packages/platformio-ide-debugger/lib/main.coffee:1:1)
    at /packages/platformio-ide-debugger/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3325206)
    at Package.activateNow (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3313190)
    at measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3312968)
    at Package.measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3310578)
```

### Commands

```
     -1:18.4.0 platformio-ide:target:build (a.stack-toggle)
```

### Non-Core Packages

```
autocomplete-clang 0.12.1 
build 0.70.0 
build-platformio 1.2.4 
busy-signal 2.0.1 
file-icons 2.1.36 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.7 
linter-ui-default 1.8.0 
platformio-ide 2.5.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.0 
```

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode https://platformio.org/platformio-ide
